###
GET http://localhost:4000/api/employees

###
POST http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Luisa",
    "position": "CEE",
    "office": "Dominican Republic",
    "salary": 20000
}

###
GET http://localhost:4000/api/employees/61d105447b1cdc024c693e4e


###
PUT http://localhost:4000/api/employees/61d105447b1cdc024c693e4e
Content-Type: application/json

{
    "salary": 23000
}

###
DELETE http://localhost:4000/api/employees/61d105297b1cdc024c693e49